name: flutter_class_parser
description: A package for serialize and deserialize common UI data classes in Flutter.
version: 0.2.5
repository: https://github.com/KevinVan720/flutter_class_parser

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
